version: "3.9"
services:
  api:
    build: .
    env_file: .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Select the OpenAI model used by the API (default: "gpt-4")
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
      # Optional Redis connection URL. Overrides host/port if set.
      - REDIS_URL=${REDIS_URL}
      # Hostname of the Redis instance used by the API (default: "redis")
      - REDIS_HOST=${REDIS_HOST:-redis}
      # Port for the Redis instance (default: 6379)
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on: [redis]
    ports: ["8000:8000"]
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  discord-bot:
    build: .
    env_file: .env
    command: ["python", "clients/discord/bridge.py"]
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      # Point the bot to the API container
      - FRENZY_API_URL=${FRENZY_API_URL:-http://api:8000}
      # Persona used by the Discord bridge (default: "blueprint-nova")
      - FRENZY_CHARACTER=${FRENZY_CHARACTER:-blueprint-nova}
    depends_on: [api]
