version: "3.9"
services:
  api:
    build: .
    env_file: .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Select the OpenAI model used by the API (default: "gpt-4o")
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      # Optional Redis connection URL. Overrides host/port if set.
      - REDIS_URL=${REDIS_URL}
      # Hostname of the Redis instance used by the API (default: "redis")
      - REDIS_HOST=${REDIS_HOST:-redis}
      # Port for the Redis instance (default: 6379)
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on: [redis]
    ports: ["8000:8000"]
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
