name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install pip-tools
        run: pip install pip-tools
      - name: Install dependencies
        run: pip install --no-cache-dir --require-hashes -r requirements-lock.txt --break-system-packages
      - name: Run tests
        run: pytest -q
      - name: Generate OpenAPI spec
        run: make openapi
      - name: Fail on OpenAPI diff
        run: git diff --exit-code openapi.json
      - name: Check requirements drift
        run: |
          pip-compile --dry-run requirements.in
          pip-compile --dry-run requirements-dev.in
